Review
esa-prl/locomotion_mode pull request #1
Opened 2020-06-24 12:59 UTC by mvoellmy

Once the code review is done, change the base branch from `empty` to `master` and merge the changes.

Usage example:
https://github.com/esa-prl/simple_rover_locomotion/pull/1

2020-07-02 17:01 UTC, wieset commented on include/locomotion_mode/locomotion_mode.hpp
> +  std::vector<std::shared_ptr<urdf::Joint>> joints_;
Seems unused in the code (only populated)

2020-07-02 17:03 UTC, wieset commented on include/locomotion_mode/locomotion_mode.hpp
> +  urdf::Pose get_parent_joint_position(std::shared_ptr<urdf::Link> & link);
```suggestion
  urdf::Pose get_parent_joint_position(const std::shared_ptr<urdf::Link> & link);
```

2020-07-02 17:10 UTC, wieset commented on src/stop_mode.cpp
> +  }
This should be in the base class constructor. But `enabled_` is initialized to `false` there, so this does nothing and can be removed.

2020-07-06 15:00 UTC, mvoellmy commented on README.md
> +Maintainer: Miro Voellmy, miro.voellmy@esa.com**
Damn, that was wrong in the template. I updated all the emails in all repos.

2020-07-10 14:10 UTC, wieset commented
In general, what I don't like is that the logic isn't separated from the Node implementation. This is what Rock tried to enforce.

I would suggest to always have a Node class that takes care of parameters, messages, pub/subs, services and have a separate class that implements the logic that is called from the Node. Otherwise, it will be a pain if we ever want to use the locomotion logic separately from the framework.

2020-10-22 16:06 UTC, wieset requested changes

2020-11-06 16:35 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +  void init_motor(std::shared_ptr<LocomotionMode::Motor> & motor, std::shared_ptr<urdf::Link> link);
Moved it into the constructor of the motor class

2020-11-06 17:01 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +    }
Changed it, so the leg is initialized with the motors directly.

2020-11-06 17:01 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +  urdf::Pose get_parent_joint_position(std::shared_ptr<urdf::Link> & link);
done

2020-11-10 14:47 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +    sensor_msgs::msg::JointState joint_state;
done

2020-11-10 14:54 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +    }
done

2020-11-10 15:48 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +    }
@wieset Would you then compile the maps from the individual legs into a massive map containing all motors?
Otherwise you still have to loop through all legs and use the `std::map::find()` on each leg to find the motor.

2020-11-10 16:11 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +{
Done.

2020-11-10 16:12 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +  RCLCPP_INFO(this->get_logger(), "Enabeling %s.", node_name_.c_str());
Done

2020-11-10 16:12 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +{
Done

2020-11-10 16:13 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +  RCLCPP_DEBUG(this->get_logger(), "Disabling %s.", node_name_.c_str());
Done

2020-11-10 16:13 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +
Done

2020-11-10 16:19 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +
@wieset I'm assuming with "other comment", you mean the same "other comment" mentioned in the comment to `rover_velocities_callback_disabled()`.

This callback has a different purpose compared to `rover_velocities_callback_disabled()` however.

This will output an warning in case a locomotion mode implementation does not overwrite the callback. I would leave it so the mistake is immediately obvious but if you don't think it's necessary, then I can remove it.

2020-11-10 16:24 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +  return tmp_link;
good find, changed it.

2020-11-10 16:26 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +  std::vector<std::shared_ptr<urdf::Link>> links_;
Changed.

2020-11-10 16:42 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +  std::shared_ptr<urdf::Link> tmp_link = std::make_shared<urdf::Link>(*link);
Perfect, changed it.

2020-11-10 16:47 UTC, mvoellmy commented on CMakeLists.txt
> +    $<INSTALL_INTERFACE:include>)
Done

2020-11-10 16:47 UTC, mvoellmy commented on CMakeLists.txt
> +  INCLUDES DESTINATION include
Done

2020-11-10 16:47 UTC, mvoellmy commented on CMakeLists.txt
> +)
Done

2020-11-10 16:49 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +  std::shared_ptr<urdf::Model> model_;
not stored anymore. model path is passed to rover class instead.

2020-11-10 17:13 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +
Done.

2020-11-12 15:59 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +  std::vector<std::shared_ptr<urdf::Joint>> joints_;
Removed it

2020-11-13 10:57 UTC, mvoellmy commented on README.md
> +	Desired linear and angular velocity of rover.
Done.

2020-11-13 10:58 UTC, mvoellmy commented on README.md
> +	This service enables the locomotion mode. The subscription to the topic `rover_motion_cmd` is deactivated. This service should only be called from the locomotion manager.
Done

2020-11-13 11:08 UTC, mvoellmy commented on CMakeLists.txt
> +add_library(${PROJECT_NAME} STATIC src/locomotion_mode.cpp)
Looked into it. Assuming performance losses of making the library dynamic are not too big (which I assume they arn't since ROS uses it as default), I agree it makes more sense to use a dynamic library as we're reusing the library a few times per rover.

2020-11-13 11:20 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +  // TARGET_POSE = {CURRENT, POSE_1, POSE_2, etc.}
Done

2020-11-13 11:57 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +  urdf::Pose transpose_pose(urdf::Pose parent, urdf::Pose child);
Done.

2020-11-13 11:58 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +  // string mode_name_;
done.

2020-11-13 12:06 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +  virtual void rover_velocities_callback(const geometry_msgs::msg::Twist::SharedPtr msg);
@wieset I can do that. It would also make very clear what the user has to implement.

Do you see any use case (in the 3D kinematics for example) where special publishing is needed? Like publishing multiple times, or not publishing every time the callback is executed?

2020-11-13 12:07 UTC, mvoellmy commented on package.xml
> +  <description>Package contains base class which provides interfaces to the rover pipeline.</description>
Done.

2020-11-13 12:07 UTC, mvoellmy commented on package.xml
> +  <version>0.0.0</version>
Bumped it to 0.0.2, 0.0.1 was before the review as the functionality was there and 0.0.2 will be this rework.

2020-11-13 12:19 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +  LocomotionMode(rclcpp::NodeOptions options, std::string node_name);
Done

2020-11-13 12:22 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +    automatically_declare_parameters_from_overrides(true)),
This currently prevents node_options from being const.

2020-11-13 12:26 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +  bool transition_to_robot_pose(std::string transition_name);
Done.

2020-11-13 12:27 UTC, mvoellmy commented on src/stop_mode.cpp
> +  }
Done.

2020-11-13 12:28 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +  sensor_msgs::msg::JointState current_joint_state_;
Removed.

2020-11-13 12:28 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +  current_joint_state_(),
Removed.

2020-11-13 12:28 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +      joint_state.name.resize(1);
Removed.

2020-11-13 13:15 UTC, mvoellmy commented on config/stop_mode.yaml
> +            dep_positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
I could imagine that a egress locomotion modes has a few poses, which could be transitioned too. So I think there's a benefit to have more poses then enable and disable. Or a simple wheel walking algorithm might profit from simple poses declared in the config.

2020-11-13 13:16 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +    automatically_declare_parameters_from_overrides(true)),
Since the poses and their names are only defined in the config file. This still requires allow_undeclared_parameters.
The overrides are defined in load_params()

2020-11-13 17:35 UTC, wieset commented on include/locomotion_mode/locomotion_mode.hpp
> +  virtual void rover_velocities_callback(const geometry_msgs::msg::Twist::SharedPtr msg);
Not really at the moment. A new twist should always result in a new joint command, except when the computation is still busy, in which case the callback should not be called at all. We should look into the subscriber queue depth for this. Invalid twists should also result in a joint command message being published, probably zero velocities for all joints, to avoid the risk of the rover just continuing its motion.

2020-11-13 17:37 UTC, wieset commented on src/locomotion_mode.cpp
> +    }
The former! One map containing all the motors. Otherwise it's no benefit :)

2020-11-18 16:35 UTC, mvoellmy commented on include/locomotion_mode/locomotion_mode.hpp
> +#define LOCOMOTION_MODE_H
done.

2020-11-18 16:37 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +    automatically_declare_parameters_from_overrides(true)),
Added issue to Changelog.

2020-11-18 16:50 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +  load_robot_model();
Done.

2020-11-18 16:51 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +void LocomotionMode::load_params()
Done.

2020-11-18 16:52 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +    }
Added as TODO to changelog.

2020-11-19 17:23 UTC, wieset approved these changes
@mvoellmy Congrats, that was a huge effort, great job! Now it's very nicely structured. Almost ready to merge :)

2020-11-19 17:42 UTC, wieset requested changes

2020-11-19 17:42 UTC, wieset commented on src/locomotion_mode.cpp
> +void LocomotionMode::rover_velocities_callback(const geometry_msgs::msg::Twist::SharedPtr msg)
```suggestion
// Callback function that publishes the rover joint commands based on the desired body velocity. Can be overwritten.
void LocomotionMode::rover_velocities_callback(const geometry_msgs::msg::Twist::SharedPtr msg)
```

Update comment

2020-11-19 17:42 UTC, wieset commented on src/locomotion_mode.cpp
> +rover_msgs::msg::JointCommandArray LocomotionMode::compute_joint_commands(
```suggestion
// Compute the rover joint commands based on the body velocity. Should be overwritten.
rover_msgs::msg::JointCommandArray LocomotionMode::compute_joint_commands(
```

Add comment to method

2020-11-19 17:42 UTC, wieset commented on CHANGELOG.rst
> +* Create template function for a frequency based execution.
```suggestion
TODO
----
* Transpose orientation and position
* Use Map for motors instead of individual objects and a vector
* Put find leg name into function
* Wait for transition to robot pose to finish

NICE TO HAVE
------------
* Create template function for a frequency based execution.
```

Move from NICE TO HAVE to TODO

2020-11-19 17:42 UTC, wieset commented on src/stop_mode.hpp
> +}
```suggestion
namespace locomotion_mode {

class StopMode : public LocomotionMode
{
public:
  StopMode(rclcpp::NodeOptions options, std::string node_name);

private:
  rover_msgs::msg::JointCommandArray compute_joint_commands(const geometry_msgs::msg::Twist::SharedPtr msg);
};
}
```

Remove indentation level inside of namespace according to style guide

2020-11-19 17:42 UTC, wieset commented on src/locomotion_mode.cpp
> +void LocomotionMode::rover_velocities_callback(const geometry_msgs::msg::Twist::SharedPtr msg)
```suggestion
// Callback function that publishes the rover joint commands based on the desired body velocity. Can be overwritten.
void LocomotionMode::rover_velocities_callback(const geometry_msgs::msg::Twist::SharedPtr msg)
```

Update comment

2020-11-19 17:42 UTC, wieset commented on src/locomotion_mode.cpp
> +  __attribute__((unused)) const geometry_msgs::msg::Twist::SharedPtr msg)
```suggestion

// Compute rover joint commands from desired body velocity. Should be overwritten.
rover_msgs::msg::JointCommandArray LocomotionMode::compute_joint_commands(
  __attribute__((unused)) const geometry_msgs::msg::Twist::SharedPtr msg)
```

Add comment

2020-11-19 20:33 UTC, wieset requested changes

2020-11-19 20:33 UTC, wieset commented on src/rover.cpp
> +                                       std::make_shared<Rover::Motor>(get_link_in_leg(link, deployment_name_)));
Did you check if this works when there is no steering joint? I'm afraid it will crash, since `get_link_in_leg()` will return an empty link, then the `Motor()` constructor will try to access `parent_joint` which will be a nullptr, leading to a segfault. Hope I'm wrong though :)

2020-11-20 13:19 UTC, mvoellmy commented on src/locomotion_mode.cpp
> +  if (enabling_sequence()) {
@wieset The enabling sequence is called here. This allows the locomotion mode to create a custom enabling or disabling transition. This could be for example commanding the robotic arm to move into it's base configuration. Another usecase I see is that when enabling the stop mode you want to stop the driving wheels. When changing between ackermann and wheelwalking, the wheels could continue spinning without having to stop first.

2020-11-20 14:45 UTC, wieset commented on src/locomotion_mode.cpp
> +  if (enabling_sequence()) {
My bad, didn't spot this. All good!

2021-01-07 18:31 UTC, merged